### ISSUE TITLE
argparse.ArgumentError: argument --remote: conflicting option string: --remote on start testing session

### ISSUE THREAD

**Issue by SI7-Agent** [CFMTech/pytest-monitor#31]
**Description**
After starting a test session the plugin crashes. There is no errors while using only pytest.
Log says its an error with argparse.

**To Reproduce**
1. Run test sessions
(i have run with "pytest --db ./monitor.db" command)

**Log**
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\pytest.exe\__main__.py", line 7, in <module>
    from connexion.decorators.uri_parsing import AlwaysMultiURIParser
  File "c:\program files\python38\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "c:\program files\python38\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "c:\program files\python38\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Users\Asus\AppData\Roaming\Python\Python38\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Users\Asus\AppData\Roaming\Python\Python38\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Users\Asus\AppData\Roaming\Python\Python38\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\Users\Asus\AppData\Roaming\Python\Python38\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\program files\python38\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\Users\Asus\AppData\Roaming\Python\Python38\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\Asus\AppData\Roaming\Python\Python38\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\program files\python38\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "c:\program files\python38\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "c:\program files\python38\lib\site-packages\_pytest\config\__init__.py", line 1175, in _preparse
    self.known_args_namespace = self._parser.parse_known_args(
  File "c:\program files\python38\lib\site-packages\_pytest\config\argparsing.py", line 146, in parse_known_args
    return self.parse_known_and_unknown_args(args, namespace=namespace)[0]
  File "c:\program files\python38\lib\site-packages\_pytest\config\argparsing.py", line 155, in parse_known_and_unknown_args
    optparser = self._getparser()
  File "c:\program files\python38\lib\site-packages\_pytest\config\argparsing.py", line 122, in _getparser
    arggroup.add_argument(*n, **a)
  File "c:\program files\python38\lib\argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "c:\program files\python38\lib\argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "c:\program files\python38\lib\argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "c:\program files\python38\lib\argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "c:\program files\python38\lib\argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --remote: conflicting option string: --remote

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (build 19042.746)
 - Version pytest-monitor 1.5.0
 - Python Version 3.8.2

**Comment by js-dieu** [comment]
Hello

Thanks for reporting. Do you have any other plugins installed?

**Comment by SI7-Agent** [comment]
Hello
Yes, i have installed: pytest-bdd, pytest-stub, pytest-mock, pytest-sugar, pytest-profiling and pytest-memprof.

**Comment by js-dieu** [comment]
Hello

This is weird... I was thinking about a plugin already using this option but I am unable to reproduce the behaviour under Linux. 
Can you just add for each plugin the version you are using ? BTW, you do not have any local plugin extending pytest options, don't you ?

**Comment by SI7-Agent** [comment]
Hello
I guess under Linux it will be working. There are lots of things perfectly running under Linux and never going under Windows
Versions of plugins are:
pytest-bdd v4.0.2
pytest-memprof v0.2.0
pytest-mock v3.5.0
pytest-profiling v1.7.0
pytest-stub v1.1.0
pytest-sugar v0.9.4
and pytest v6.2.1
What does mean "local plugin extending pytest option"? If that means that it's installed for the local user, i can't be sure. All of them had been installed locally for user, not admin.
//But I guess something is wrong with Windows XD//

**Comment by js-dieu** [comment]
Thanks a lot.

Agree. It is likely that we fall under some circumstances under Windows. I'll try to have a look by end of week.

**Comment by js-dieu** [comment]
Hello

Unfortunately, I am unable to reproduce. After having installed the plugins you indicated, i got the following output:
```bash
 H:\projects\dummy>pytest --db monitor.db
Test session starts (platform: win32, Python 3.8.6, pytest 6.2.1, pytest-sugar 0.9.4)
rootdir: H:\projects\dummy, configfile: pytest.ini
plugins: bdd-4.0.2, memprof-0.2.0, mock-3.5.1, monitor-1.5.0, profiling-1.7.0, stub-1.1.0, sugar-0.9.4
collecting ... 
```
and the test suite completes.
Do you have any overloading of the cli parameters by any custom plugin (conftest for instance) ?
From my understanding, there is another plugin using the option `--remote`. I've checked the code of the plugins you listed and none of them seems to define this option.
